### ISSUE TITLE
Experience label colors

### ISSUE THREAD

**Issue by chachmu** [RoboJackets/robocup-common#2]
Currently the color for experience labels for common is different from the color for firmware instead matching the color of "needs-electrical". The rest of the colors are standardized across the repos which makes a lot more sense.

**Comment by jgkamat** [comment]
Ah yah thats my bad, I'm on it.

**Comment by jgkamat** [comment]
I may or may not be colorblind, so let me know if there still are issues, but I'll close this for now (hex codes for experience is the same for both repos now)
